apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: default
data:
  config.hcl: |
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
    storage "mysql" {
      address  = "10.17.10.10"
      username = "vault"
      password = "password"
      database = "k8s_vault"
    }
  vault_addr: "http://0.0.0.0:8200"
  vault_api_addr: "http://0.0.0.0:8200"
